# Generated by Django 5.2 on 2025-05-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
